name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: react_ui_v2/yarn.lock
      - run: yarn
        working-directory: ./react_ui_v2
      - run: yarn build
        working-directory: ./react_ui_v2
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: react_ui_v2/yarn.lock
      - run: yarn
        working-directory: ./react_ui_v2
      - run: yarn lint
        working-directory: ./react_ui_v2
